import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Itim } from "next/font/google";

import LayoutStructure from "@/components/layout/LayoutStructure";
import { QueryProvider } from "@/provider/QueryProvider";
import { Toaster } from "sonner";

const itim = Itim({
  variable: "--font-itim",
  weight: "400"
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${itim.variable} font-itim h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <main className="flex items-center justify-center flex-col gap-1 text-xl h-screen text-gray-400">
            <LayoutStructure>
              {children}
            </LayoutStructure>
          </main>
          <Toaster richColors />
        </QueryProvider>
      </body>
    </html>
  );
}
